spring:
  application:
    name: api-gateway
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  flyway:
    enabled: true

server:
  port: 8080

jwt:
  secret: sedekahku-secret-key-must-be-at-least-256-bits-long-for-hs256
  expiration: 86400000

logging:
  level:
    com.sedekahku.gateway: DEBUG